#
#	Global configuration for SNAP makefiles
#

GLIB = glib-core
SNAP = snap-core
SNAPADV = snap-adv

CGLIB = ../$(GLIB)
CSNAP = ../$(SNAP)

EXGLIB = ../../$(GLIB)
EXSNAP = ../../$(SNAP)
EXSNAPADV = ../../$(SNAPADV)

UNAME := $(shell uname)

ifeq ($(UNAME), Linux)
  # Linux flags
  CC = g++
  CXXFLAGS += -std=gnu++1y -Wall
  CXXFLAGS += -O3 -DNDEBUG -fopenmp -rdynamic 
  # CXXFLAGS += -O0 -DNDEBUG -fopenmp
  # turn on for crash debugging, get symbols with <prog> 2>&1 | c++filt
  # CXXFLAGS += -g -rdynamic -fsanitize=address
  # CXXFLAGS += -ggdb
  # turn on for OpenMP
  CXXOPENMP = 
  LDFLAGS +=
  LIBS += -lrt

endif
